import re
import os

filepath = 'backend/alembic/versions/6184d3df3864_initial_schema.py'
with open(filepath, 'r') as f:
    content = f.read()

# Add Inspector logic
content = content.replace('def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###', 
'''def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()''')

# Wrap each create_table in an if statement
def wrap_table(match):
    table_name = match.group(1)
    return f"    if '{table_name}' not in tables:\n        op.create_table('{table_name}',"

content = re.sub(r"    op\.create_table\('([^']+)',", wrap_table, content)

# Indent the bodies
lines = content.split('\n')
inside_if = False
for i, line in enumerate(lines):
    if line.startswith('    if '):
        inside_if = True
    elif inside_if and line.startswith('    def downgrade'):
        inside_if = False
        
    if inside_if and not line.startswith('    if '):
        if line.startswith('    op.') or line.startswith('    sa.'):
            lines[i] = '    ' + line
        elif line == '    )':
            lines[i] = '        )'

content = '\n'.join(lines)

with open(filepath, 'w') as f:
    f.write(content)
